### PR TITLE
Fix rtsp static rtsp sink

### LINKED ISSUE #210: RTSP is broken in t3.11.0 for Raspberry Pi
The symptom is a timeout when creating h264 RTSP streams. The fail rate is much higher than the success rate, so this is a critical bug.

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**
Fixes #210 by connecting sinks before starting the pipeline.

Don't merge it yet as I'm still testing all cases.

Tests:
- [x] RTSP h264 1080p 30fps + with multiple WebRTC clients
- [x] UDP h264 1080p 30fps + with multiple WebRTC clients
- [x] stress streams creation
- [x] stress thumbnails
- [x] RTSP with other encodings, sizes and fpss
- [x] UDP with other encodings, sizes and fpss

### CODE REVIEW

File: src/stream/pipeline/runner.rs [hunk 1]
```diff
@@ -26,8 +27,11 @@ impl PipelineRunner {
         let pipeline_weak = pipeline.downgrade();
         let (killswitch_sender, _killswitch_receiver) = broadcast::channel(1);
         let watcher_killswitch_receiver = killswitch_sender.subscribe();
+        let (start_signal_sender, start_signal_receiver) = broadcast::channel(1);
```
Comment (joaoantoniocardoso) [inline src/stream/pipeline/runner.rs:30]: just to point out that while solutions using the `oneshot` channel or `barrier` would have solved it, the `broadcast` channel is the easiest to deal with without fighting with async.

**Review by patrickelectric — APPROVED** [review]

**Comment by patrickelectric** [comment]
@joaoantoniocardoso please create the release and prepare it to BlueOS, I would like to create a new version with it ASAP.

**Comment by aihamshikhomicro** [comment]
Hello,
I don't know if this is the right place to ask my question but it's not an actual issue so I'll ask it here.
How do I create a redirect stream from a rtsp IP camera stream?
I created a gstreamer pipline to receive it and it's working fine, but how do I create a MAVLINK stream from it? the device in the UI for redirect source is a fixed text, where do I specify my rtsp link an create a redirect out of it?

**Comment by joaoantoniocardoso** [comment]
Hi @aihamshikhomicro, I moved it to a new issue, I'll respond it there.
