### PR TITLE
Fix settings

### LINKED ISSUE #81: Failing to load settings between versions
for more information: https://github.com/bluerobotics/BlueOS-docker/issues/1030

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**
Closes #81 by resetting the settings if incompatible, but before, it creates a simple copy as a backup.

### CODE REVIEW

File: src/settings/manager.rs [hunk 1]
```diff
@@ -110,14 +110,15 @@ fn fallback_settings_with_backup_file(file_name: &str) -> SettingsStruct {
 
 fn load_settings_from_file(file_name: &str) -> SettingsStruct {
     let result = std::fs::read_to_string(file_name);
-
-    debug!("loaded!");
-    if result.is_err() || cli::manager::is_reset() {
```
Comment (patrickelectric) [inline src/settings/manager.rs:106]: What about the reset ?

File: src/settings/manager.rs [hunk 2]
```diff
@@ -72,13 +72,17 @@ impl Manager {
             file_name.into()
         };
 
-        debug!("Using settings file: {}", &file_name);
-
-        let settings = load_settings_from_file(&file_name);
+        let config = if cli::manager::is_reset() {
```
Comment (patrickelectric) [inline src/settings/manager.rs:75]: I see

**Review by patrickelectric — APPROVED** [review]

File: src/settings/manager.rs (hunk 1 above)
Comment (joaoantoniocardoso) [reply src/settings/manager.rs:106]: It has moved to the function that calls it
